{% set version = "19.4.1" %}

package:
  name: pyaml
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyaml/pyaml-{{ version }}.tar.gz
  sha256: c79ae98ececda136a034115ca178ee8bf3aa7df236c488c2f55d12f177b88f1e

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip

  run:
    - python
    - pyyaml

test:
  imports:
    - pyaml
    - pyaml.tests

about:
  home: https://github.com/mk-fg/pretty-yaml
  license: WTFPL
  license_file: COPYING
  summary: 'PyYAML-based module to produce pretty and readable YAML-serialized data'
  dev_url: https://github.com/mk-fg/pretty-yaml
  doc_url: https://github.com/mk-fg/pretty-yaml

extra:
  recipe-maintainers:
    - pmlandwehr
