{% set name = "pyaml" %}
{% set version = "25.5.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5799560c7b1c9daf35a7a4535f53e2c30323f74cbd7cb4f2e715b16dd681a58a

build:
  skip: true  # [py<38]
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv"

requirements:
  build:
    - python
    - pip
  host:
    - python
    - setuptools
    - pip
    - wheel
  run:
    - python
    - pyyaml

test:
  source_files:
  # Must include entire folder rather than just 'tests' one, due to tests looking
  # for Python type names prefixed with 'pyaml.tests'
    - pyaml
  requires:
    - pip
    - pytest
  imports:
    - pyaml
    - pyaml.tests
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -vv pyaml/tests

about:
  home: https://github.com/mk-fg/pretty-yaml
  license: WTFPL
  license_file: COPYING
  summary: 'PyYAML-based module to produce pretty and readable YAML-serialized data'
  description: 'PyYAML-based python module to produce a bit more pretty and human-readable YAML-serialized data.'
  dev_url: https://github.com/mk-fg/pretty-yaml
  doc_url: https://github.com/mk-fg/pretty-yaml

extra:
  recipe-maintainers:
    - pmlandwehr
