# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "YQB/YNhFpvTBEuT5WHKx++gGwTN1XfwJAs9ASbWnhrDRI6Q/DE41ogfDlEv43fKdzmwJR0Vp0XtXi/nQ2yWapzy4f1DsTcGb6K51+PiWGIsrRPjWyFz4RVoZmTf+b8cZ+OumxwNIZtMF04QCPVWZS6nNhQ26FEKgOU517Z5bpf5E2IRZ+CMGLkNffPcKp9Bs8Q8tVJ+5/UP2/kSE9KJB4/5QwQYYbLZe0uJwGo2HLXoKxEdtw6uEyCmkt+VBXCQIQMXKRS+DGJGSRKfURySrptWPA8jOuMojvOcg4j8V7m++ogBaB2ypOSf+heMREitiQcOY2xd7UtGrNjOjKLriVR0PZiq5k/7EuP5KmvWxfuzFyKXwjjTdPopxwp2ezuHLJuSnmkt7KxN7MBm+FbjLWboDqYKh4AOxx8yhNvOT+YUS7gNMbCg5cXwqudT/AH6yI/RaOY0coycLFXcFiuUv9KGni+QTeg9XJzgFfT0WEB4h0t9mSGyx4ZhGZzcH8m8upqW9ZkJzjj5tQCZ0XtY0OALI1saIdB2+7mQK/qmeRFEfPhLdXMNBTVpTAoj/PSA23N3Vrm9VT2Oitf40QuUEhnHCn7CDdcrtS0f975eaxzc1UFwT5mI3s4srY2+BV76BaeSqplPacXn+Uw6g5l9aODbSEQZr2clLGKDUnaXQ9C4="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
