travis:
  secure:
    BINSTAR_TOKEN: YQB/YNhFpvTBEuT5WHKx++gGwTN1XfwJAs9ASbWnhrDRI6Q/DE41ogfDlEv43fKdzmwJR0Vp0XtXi/nQ2yWapzy4f1DsTcGb6K51+PiWGIsrRPjWyFz4RVoZmTf+b8cZ+OumxwNIZtMF04QCPVWZS6nNhQ26FEKgOU517Z5bpf5E2IRZ+CMGLkNffPcKp9Bs8Q8tVJ+5/UP2/kSE9KJB4/5QwQYYbLZe0uJwGo2HLXoKxEdtw6uEyCmkt+VBXCQIQMXKRS+DGJGSRKfURySrptWPA8jOuMojvOcg4j8V7m++ogBaB2ypOSf+heMREitiQcOY2xd7UtGrNjOjKLriVR0PZiq5k/7EuP5KmvWxfuzFyKXwjjTdPopxwp2ezuHLJuSnmkt7KxN7MBm+FbjLWboDqYKh4AOxx8yhNvOT+YUS7gNMbCg5cXwqudT/AH6yI/RaOY0coycLFXcFiuUv9KGni+QTeg9XJzgFfT0WEB4h0t9mSGyx4ZhGZzcH8m8upqW9ZkJzjj5tQCZ0XtY0OALI1saIdB2+7mQK/qmeRFEfPhLdXMNBTVpTAoj/PSA23N3Vrm9VT2Oitf40QuUEhnHCn7CDdcrtS0f975eaxzc1UFwT5mI3s4srY2+BV76BaeSqplPacXn+Uw6g5l9aODbSEQZr2clLGKDUnaXQ9C4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
