travis:
  secure:
    BINSTAR_TOKEN: Ihfa4JBeM8pMY2F4wV301kNl7TdvFkup5NJ5IjrSuUmtf7PSJo44ILdVdhF8BOBPZ08PKAYrR663MLZrHn6G6mkvR/r9sA3xheAlPsOyVCWB/f1ndAq0zehfdLQDuMXK4PE9phZnpORo6CJET3eh1+Y/E0Ik3fDP7aqC306HaqzliJNev31z7H8L+rcmFlSArUKFxXpRKsjzADXw8OMObvVNggIEsCsAPA1j98fw7RaUX3VilQsQby7i/OkhnJb2FBnHbSVKs5L2VWE0NVnGAD1yUMScTNqiE1WW2CqcEkgk2UglXpt7t6cEpxXP4uqt8cylO3NeZVK07mEaDbQGsAgLTovyT1Lf62u964pH2Ps39cG4MrsJlhA/coSBca/8XiBdR+o54Z0TGN2fmeNeQKfZ2U8AvpFPhPGdONXaT1grbbqqQBC0t83Dr9EoFCkl5ATOLTZk39l1XH8T779/Rp1ggx8bbCmIuKUjyP/rrQUARQkdXP4P8wAVyqHU+VQZvFjcHTHvjy/f4FHgDc8j4US7FU+sKzSFLkavlwfAo48OedEA9KKWHlguNd3m7qKGX9qgUX/nbz4/yEOOSnW+KClZMPbKC7vZQg5AMHLPaOnP0PT5O+md1Ga/E66MmRn0yuegvNuYT4blU9LmBkbY6RWZwsWRFhCGwLjcUILojVY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
